# Generated by Django 5.0.1 on 2024-05-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gross_pay',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_deductions',
            field=models.FloatField(null=True),
        ),
    ]
