# Generated by Django 4.2.9 on 2024-05-11 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_employee_gross_pay_payslip_total_deductions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gross_pay',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='total_deductions',
        ),
    ]
