# Generated by Django 4.2.9 on 2024-05-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0003_remove_employee_gross_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gross_pay',
            field=models.FloatField(null=True),
        ),
    ]
